---
- name:   Install CSF
  hosts:  vpn
  become: yes
  become_user: ocserv

  tasks:
  - name: Download csf
    shell: sudo wget https://download.configserver.com/csf.tgz -P /opt
  
  - name: Extract csf
    shell:  sudo tar -xvzf /opt/csf.tgz -C /opt 

  - name: disable and stop firewalld
    shell:  sudo systemctl disable firewalld && sudo systemctl stop firewalld
    ignore_errors: yes

  - name: set global_ip for cfs
    shell: sed -i "s/<global_ip>/{{ ansible_default_ipv4.address }}/g" ~/.uploadedFiles/csfpre.sh