---
- name:   update linux server
  hosts:  vpn
  become: yes

  tasks:
  - block:
    - apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    when: ansible_os_family == "Debian"
  - block:
    - yum:
        name: '*'
        state: latest
        update_cache: true
    when: ansible_os_family == "RedHat"